In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
#warnings.simplefilter(action='ignore', category=np.VisibleDeprecationWarning)

# Simulation

Let's play a game: we each roll a die. 

If my number is bigger: you pay me a dollar.

If they're the same: we do nothing.

If your number is bigger: I pay you a dollar.

Steps:
1. Find a way to simulate two dice rolls.
2. Compute how much money we win/lose based on the result.
3. Do steps 1 and 2 10,000 times.

# Random Selection

In [10]:
# Can make random choices from an array
coin = make_array('heads', 'tails')
np.random.choice(coin)

'tails'

In [115]:
d6 = np.arange(1, 7)
np.random.choice(d6)

6

In [27]:
d6

array([1, 2, 3, 4, 5, 6])

## Comparison ##

In [28]:
3 > 1

True

In [29]:
3 < 1

False

In [31]:
# Single equals (assignment equals) is for assigning to a variable.
# Double equals (comparison equals) is for asking whether two quantities are equal.
3 == 3

True

In [ ]:
3 == 3

In [32]:
one = 1
two = 2

In [33]:
# equal
one == 1

True

In [34]:
# less or equal
one <= one

True

In [35]:
# the "and" of two statements is true only when both are
one == one and two > one

True

In [36]:
one == one and one > two

False

In [37]:
# the "or" of two statements is true if at least one of them is true
one < two or two < one

True

In [38]:
# the "not" of a statement is the opposite truth value of the statement on its own
not(one >= two)

True

## Conditional Statements

In [39]:
age = 20

In [40]:
if age >= 18:
    print('You can legally vote.')

You can legally vote.


In [42]:
if age >= 21:
    print('You can legally drink.')

In [43]:
def age(x):
    if x >= 18:
        return 'You can legally vote.'
    if x >= 21:
        return 'You can legally drink.'

In [44]:
age(3)

In [45]:
age(20)

'You can legally vote.'

In [46]:
# A function terminates as soon as it hits its first return value.
age(25)

'You can legally vote.'

In [47]:
def age(x):
    if x >= 21:
        return 'You can legally vote and drink.'
    elif x >= 18:
        return 'You can legally vote.'
    else:
        return 'You can legally drink milk.'

In [48]:
age(3)

'You can legally drink milk.'

In [49]:
age(20)

'You can legally vote.'

In [50]:
age(23)

'You can legally vote and drink.'

# Practice

Write a function called "simulate_one_round". It takes no inputs. \
Simulate a d6 roll for yourself and another for your opponent. \
If your roll is larger, return 1.\
If your roll is smaller, return -1.\
Otherwise, return 0.

In [136]:
def simulate_one_round():
    
    me = np.random.choice(d6)
    player_two= np.random.choice(d6)

    if me > player_two:
        return 1
    elif me < player_two:
        return -1
    else:
        return 0

simulate_one_round()

-1

In [163]:
def game_of_ten():

    sum = 0

    for i in np.arange(10):
        sum = sum + simulate_one_round()

    return sum

game_of_ten()

-4

# Iteration

In [125]:
# A for loop sends a variable through an array taking on each value one at a time.
# The code in the loop is executed one time per value.
pets = make_array('cat', 'dog', 'rabbit')

for x in pets:
    print('I love my ' + x)
    print(x + 's are great')
print('pets are fun')

I love my cat
cats are great
I love my dog
dogs are great
I love my rabbit
rabbits are great
pets are fun


In [128]:
# It's common to use the array just to count the number of times you've executed.
# Notice the variable i is not used anywhere.
for i in np.arange(5):
    print('hello')
    print(i)
print('for loop over')

hello
0
hello
1
hello
2
hello
3
hello
4
for loop over


In [129]:
# You can do summation with a for loop.
sum = 0 # initialize the variable or Python will complain
for i in np.arange(1,5):
    sum = sum + i
    print(sum)
print('summation finished')

1
3
6
10
summation finished


# Practice

Write a function called ten_thousand_simulations. It takes no inputs.\
Use a for loop to call the function simulate_one_round ten thousand times. \
Sum up your total winnings by adding all the outputs togther.\
Return the sum.


In [168]:
def ten_thousand_simulations():

    winnings = 0

    for i in np.arange(10000):
        game_result = simulate_one_round()
        winnings = winnings + game_result

    return winnings

In [186]:
ten_thousand_simulations()

43

In [192]:

def simulate_until_target():

    winnings = 0
    rounds_played = 0

    while True:
        game_result = simulate_one_round()
        winnings = winnings + game_result
        rounds_played += 1

        if winnings >= 1000:
            print('Big win')
            break

        if winnings <= -1000:
            print('Crossed loss floor')
            break


    return winnings, rounds_played

simulate_until_target()

Big win


(1000, 415109)

# Appending Arrays

What if we wanted to keep a list of all the outcomes of the simulation, not just the sum?

In [193]:
nums = make_array()
for i in np.arange(1, 5):
    nums = np.append(nums, i)
    print(nums)

nums

[ 1.]
[ 1.  2.]
[ 1.  2.  3.]
[ 1.  2.  3.  4.]


array([ 1.,  2.,  3.,  4.])

# Practice

Modify ten_thousand_simulations so that it returns an array containing all ten thousand outcomes.

## Visualizing a Simulation

In [ ]:
outcomes = ten_thousand_simulations()
results_table = Table().with_column('My winnings', outcomes)
results_table.show(10)

In [ ]:
results_table_grouped = results_table.group('My winnings')
results_table_grouped.show()

In [ ]:
results_table_grouped.barh('My winnings')